{
 "title": "DispatcherSilo",
 "tags": [
  "Octopus",
  "Dispatcher"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "jobs", "label": "jobs", "query": "${VAR_JOBS}" },
   {
    "name": "instances",
    "label": "Instances",
    "query": "label_values(process_num_threads{job =~ \"$jobs\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Process basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"$jobs\", instance=~\"$instances\"}[3m])) * 100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=~\"$jobs\", instance=~\"$instances\"} /1024/1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{job =~ \"$jobs\", instance =~ \"$instances\"} /1024/1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC collection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total{job=~\"$jobs\", instance=~\"$instances\"}[1m])",
     "legendFormat": "Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{job=~\"$jobs\", instance=~\"$instances\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_handles{job=~\"$jobs\", instance=~\"$instances\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Silo runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Grain activation count",
   "type": "graph",
   "description": "Count of grain activation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(orleans_metrics{instance=~\"$instances\", category=\"Grain\",name=~\"Grain.Octopus.Dispatcher.Grains..+\"}, \"grain_type\", \"$1\", \"name\", \"Grain.Octopus.Dispatcher.Grains.(.+).Current\")",
     "legendFormat": "{{grain_type}}({{instance}})"
    }
   ]
  },
  {
   "title": "Message processd/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(orleans_metrics{job =~ \"$jobs\", instance =~ \"$instances\", name=\"Messaging.Processing.Dispatcher.Processed.Total.Current\"}[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "Message error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(orleans_metrics{job =~ \"$jobs\", instance =~ \"$instances\", name = \"Messaging.Processing.Dispatcher.Processed.Errors.Direction.Response.Current\"}[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total storage write/s",
   "type": "singlestat",
   "description": "In three minutes",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(orleans_metrics{job =~ \"$jobs\", instance =~ \"$instances\", name = \"Storage.Write.Total.Current\"}[3m]))"
    }
   ]
  },
  {
   "title": "Total storage read/s",
   "type": "singlestat",
   "description": "In three minutes",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 35 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(orleans_metrics{job =~ \"$jobs\", instance =~ \"$instances\", name = \"Storage.Read.Total.Current\"}[3m]))"
    }
   ]
  },
  {
   "title": "Storage write latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(orleans_metrics_duration_bucket{job =~ \"$jobs\", instance =~ \"$instances\", name=\"Storage.Write.Latency.Current\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Storage read latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(orleans_metrics_duration_bucket{job =~ \"$jobs\", instance =~ \"$instances\", name=\"Storage.Read.Latency.Current\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}